--- 
clone: 
  depth: 1
kind: pipeline
name: ZyCPipeline
concurrency:
  limit: 6
steps: 
  - 
    commands: 
      - "bash do-now.sh 'aarch64-zyc-linux-gnu' '12' 'arm64' 'nozip'"
    environment: 
      BOT_TOKEN:
        from_secret: BOT_TOKEN
      GIT_SECRET:
        from_secret: GIT_SECRET
    image: zycromerz/kerneldocker:v3
    name: ZyC-Build
    trigger: 
      branch: 
        - unified-tes